### PR TITLE
Wiki updates (Sidebar and Gallery)

### PR DESCRIPTION
**Pull request by AlvinSchiller**
PR to introduce some wiki and corresponding v2 repo changes.

Wiki changes can be seen here https://github.com/AlvinSchiller/RPi-Jukebox-RFID/wiki and will be merged together (updated files are _Sidebar.md, GALLERY.md, Home.md and img/gallery/calendar)

### Updates
- Sidebar
  - Add main section links for versions 2 and 3 to the wiki sidebar
    - existing pages are moved to extendable details
  - Add "gallery" as seperate entry (make it more present)
  - Add branch links for v2 to readme
- Update wiki gallery
  - Update descriptions and links
  - Move Calenders to wiki gallery and add pdf files
  - Duplicate latest calender as "latest-*.jpg"-file and link to it from main repo readme (making future updates simpler as only the wiki needs to be updated). Also update description to be generic.
  - Remove duplicate images (repo and wiki) and change links to wiki images
  - Add links to existing "design" tickets
  - Add video section from readme
- Remove links to `gitter` from readme
- Update description and links for `matrix` (aligned with description from the "new issue" section)

#### Sidebar
feature_updateWiki_Sidebar2 1 feature_updateWiki_Sidebar2 2

#### Gallery
feature_updateWiki_Gallery1

...

feature_updateWiki_Gallery2

### CODE REVIEW

**Comment by s-martin** [comment]
Do I understand it correctly that the future3 sidebar section are only links to the markdown docs in the repo?

**Comment by AlvinSchiller** [comment]
> Do I understand it correctly that the future3 sidebar section are only links to the markdown docs in the repo?

Yep, the main documentation remains in the repo (will also try to move as much v2 docs as possible in upcoming changes). 
User hacks, very specific manuals and howto's not bound to the code can still be added to the wiki by every user.

Like mentioned in https://github.com/MiczFlor/RPi-Jukebox-RFID-Miscellaneous/issues/3#issuecomment-1881015537

**Comment by AlvinSchiller** [comment]
Any addition /changes or good to go?

**Comment by s-martin** [comment]
Good to go

**Pull request merged**
