### PR TITLE
Remote control with MQTT

### PR DESCRIPTION
**Pull request by andreasbrett**
First implementation of https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/581

- depends on paho-mqtt lib (`pip3 install paho-mqtt`)
- can connect via user/password or certificate-based authentication
- to be done
   - create service file
   - include in install script

### CODE REVIEW

**Comment by MiczFlor** [comment]
Hi @andreasbrett 
could you write here a few lines about how to operate this? As I said, I have no smart home...
It's a daemon, so it should be started. Even without the install script, how would that be done manually? I can then make an attempt to include it in the install script.
Thank! micz

**Comment by andreasbrett** [comment]
@MiczFlor of course, let me see...

# Starting the daemon
The daemon is run by executing the **daemon_mqtt_client.py** script. It's just like the rfid reader daemon script and will run in an endless loop.

# How it works
Phoniebox' MQTT client connects to the MQTT server that is defined in the `SETTINGS` section of the script itself. It is able to connect by authenticating via

1) user/password or 
2) with server/client certificates

depending on what the server expects (typically Mosquitto by Eclipse is used as a MQTT server in the smart home communities). Once connected it will publish messages to the `mqttBaseTopic` that is defined in `SETTINGS` (defaults to `phoniebox`). Other MQTT clients that are e.g. part of a smart home solution can listen and respond to this base topic and its sub-topics.

Phoniebox' MQTT client will do the following things:

1. at startup send state and version info about Phoniebox to
   - `mqttBaseTopic/version` (e.g. 1.2-rc1)
   - `mqttBaseTopic/edition` (e.g. classic)
   - `mqttBaseTopic/state` (online)
2. at shutdown send state info to
   - `mqttBaseTopic/state` (offline)
3. periodically send attributes to `mqttBaseTopic/attributes/$attributeName` (interval in seconds is defined in `refreshInterval`)
4. listen for attribute requests on `mqttBaseTopic/get`
5. listen for commands on `mqttBaseTopic/set`

## mqttBaseTopic/get
MQTT clients can request an attribute of Phoniebox. Sending a payload of e.g. `volume` to `mqttBaseTopic/get` will trigger Phoniebox' MQTT client to fetch the current volume from MPD and send the result to `mqttBaseTopic/attributes/volume`. 

### Possible attributes
- volume
- mute
- repeat
- random
- state
- file
- artist
- albumartist
- title
- album
- track
- elapsed
- duration
- trackdate
- last_card

### Help
Sending payload `help` will be responded by a list of all possible attributes to `mqttBaseTopic/available_attributes`

## mqttBaseTopic/set
MQTT clients can send commands to Phoniebox. Sending a payload of e.g. `volumeup` to `mqttBaseTopic/set` will trigger Phoniebox' MQTT client to send that command to `playout_controls.sh`.

### Possible commands
- volumeup
- volumedown
- mute
- playerpause
- playernext
- playerprev

### Help
Sending payload `help` will be responded by a list of all possible commands to `mqttBaseTopic/available_commands`

**Comment by MiczFlor** [comment]
Hi @andreasbrett 
thanks for the contribution!!!
Please have a look here at the wiki and possible make changes as your work progresses.
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Smart-Home-remote-control-with-MQTT
I will merge this to master now, because it's not interferring with anything else.

**Comment by Piehti** [comment]
Awesome. Guess I got to give it another try. Last one failed. Stuck with a working MQTT polling.

**Pull request merged**
