### PR TITLE
Gpio control to class, fixing usb_button support

### PR DESCRIPTION
**Pull request by arne123**
Dear all, I tired to solve the issue #1318,
unfortunately I could not do any meaningful testing here, I was basically typing in the dark.
At least map_buttons_usb_encoder.py prints now something, so for me it seems the refactored functions calls are imported properly.
Please support me in testing for this PR.

### CODE REVIEW

**Review by s-martin — APPROVED** [review]
Couldn’t test it, but looks ok ( looks at least the same as other working code)

**Comment by s-martin** [comment]
@derchan could you check, if this fixes the issue for you?

**Comment by derchan** [comment]
Made a quick on checkout and looks good!
Will do a clean install in a few days and re-check.

**Comment by derchan** [comment]
ok checkout your branch and sadly it did not work.

pi@chanorama:~/RPi-Jukebox-RFID $ sudo ./components/controls/buttons_usb_encoder/setup-buttons-usb-encoder.sh
Please make sure that the Buttons USB Encoder and the buttons are connected before continuing...
Continue (y/n)? y

Choose the Buttons USB Encoder device from the list
0 DragonRise Inc.   Generic   USB  Joystick
1 C-Media Electronics Inc. USB Audio Device
2 HXGCoLtd Keyboard
Device Number: 0

During the next step you can map your buttons to one of the following available functions:
[]

Ready to continue? (y/n)

**Comment by arne123** [comment]
would you be so kind and tryout directly calling the pythonscript?

in my case it looks like this (if I omit the import of the usb specific items)

> **RPi-Jukebox-RFID$ python3 components/controls/buttons_usb_encoder/map_buttons_usb_encoder.py** 
> During the next step you can map your buttons to one of the following available functions:
> ['PlayerNext', 'PlayerPause', 'PlayerPauseForce', 'PlayerPrev', 'PlayerSeekBack', 'PlayerSeekFwd', 'PlayerStop', 'R
> ecordPlayLatest', 'RecordStart', 'RecordStop', 'Shutdown', 'ToggleWifi', 'Vol0', 'VolD', 'VolU']
> Ready to continue? (y/n)n
> Aborted mapping buttons to functions

when there is also nothing, I would like to ask you to add this line in the map_buttons_usb_encoder.py 
`print(dir(components.gpio_control.function_calls.phoniebox_function_calls))`

directly after the imports and call the script again

Sorry for bother you with remote debugging

**Comment by derchan** [comment]
> would you be so kind and tryout directly calling the pythonscript?
> 
> in my case it looks like this (if I omit the import of the usb specific items)
> 
> > **RPi-Jukebox-RFID$ python3 components/controls/buttons_usb_encoder/map_buttons_usb_encoder.py**
> > During the next step you can map your buttons to one of the following available functions:
> > ['PlayerNext', 'PlayerPause', 'PlayerPauseForce', 'PlayerPrev', 'PlayerSeekBack', 'PlayerSeekFwd', 'PlayerStop', 'R
> > ecordPlayLatest', 'RecordStart', 'RecordStop', 'Shutdown', 'ToggleWifi', 'Vol0', 'VolD', 'VolU']
> > Ready to continue? (y/n)n
> > Aborted mapping buttons to functions
> 
> when there is also nothing, I would like to ask you to add this line in the map_buttons_usb_encoder.py
> `print(dir(components.gpio_control.function_calls.phoniebox_function_calls))`
> 
> directly after the imports and call the script again
> 
> Sorry for bother you with remote debugging

@arne123  kein Problem. 

gib mir etwas das ordentlich zu testen. Ich ziehe mir deine komplette Repro einmal.

**Comment by derchan** [comment]
@arne123 
- So habe mir nochmal deine repo komplett von deinem remote gezogen. 
- Bin dann auf deinen branch gewechselt
- reset und clean durchgeführt
- alle meine uncommited changes weggeworfen.

setup script und python script gehen.

Es scheinen aber noch nicht die richtigen calls abzusetzen 
Auch nach Neustart werden die gemappend befehle nicht weitergeleitet bzw. aufgerufen.
Tippen der Buttons hat keine Auswirkung. 
Hast du den richtigen Funkionsaufruf?

**Comment by derchan** [comment]
@s-martin @arne123 
mal ein bisschen rumgespielt und habe nur Grundkenntnis in Python...
Kann es diese Stelle hier sein? 
`import components.gpio_control.function_calls`

nach Python Doku wäre folgendes eventuell besser? 
`from components.gpio_control.function_calls import phoniebox_function_calls`

**Comment by arne123** [comment]
@derchan fixed a remaining bug, please refer to pr #1323

**Pull request closed without merging**
