### PR TITLE
Make master py3 compatible 

### PR DESCRIPTION
**Pull request by s-martin**
Making master also Python3 compatible, so Python 2 packages could also be dropped on master.

### CODE REVIEW

**Comment by MiczFlor** [comment]
Hi @s-martin @ZyanKLee 
not sure when I will be ready to really test this to the fullest. If it's urgent / running / tested, please feel free to merge.

**Comment by s-martin** [comment]
I need to remove the /use/bin/python3 commands in the systems scripts

**Comment by s-martin** [comment]
added all necessary changes

**Comment by ZyanKLee** [comment]
Is python2 a raspbian dependency or can this be removed completely?

**Comment by s-martin** [comment]
I think it's a Raspian dependency.

**Comment by s-martin** [comment]
From what I've googled this afternoon, Python2 is still required by Raspian/Debian.

If I read [this ](https://wiki.debian.org/Python/2Removal) correctly, Python 2 removal will be done in current unstable release (which means 2 releases after buster). So at the moment, we shouldn'T try to remove Python 2 altogether.

**Pull request merged**
