### PR TITLE
Update Documentation

### PR DESCRIPTION
**Pull request by AlvinSchiller**
I started to update / harmonise the documentation.
This includes the source and the wiki repo. 
Renamings have been made in both (if existing). 

**As the wiki repo does not support Branches or PullRequest the dev state can be seen here:
Git: https://github.com/AlvinSchiller/RPi-Jukebox-RFID.wiki.git
Wiki: https://github.com/AlvinSchiller/RPi-Jukebox-RFID/wiki**

The change includes:
- [x] Move docs from source repo to wiki
- [x] Update deprecated RPi OS distro names (and even remove in places where not neccessary -> see Question 'file renaming')
- [x] Harmonise installation guide (e.g. links to RPi OS Images, Image flashing, etc...)
- [x] Fix / remove links to deprecated docs / installscripts

Questions
- Some files will better be renamed, but this would break links in existing issues / discussions / branches (e.g. master).
Should the old files persist and only link to the new ones, or is this acceptable?

### CODE REVIEW

**Comment by AlvinSchiller** [comment]
@s-martin Before i continue and deep dive is this desirable? And are there maybe other edge cases that have to be considered?

**Comment by s-martin** [comment]
Hi, sorry for the late reply.

Thanks for making the effort. From my point of view it absolutely makes sense.

Future3 already has a thorough Sphinx / readthedocs documentation, but I think V2 needs some polishing!

**Comment by AlvinSchiller** [comment]
> Nevertheless I would keep the components docs in the repo as this is often installed optionally and it’s important to keep the source code and the docs in sync.

Totally agree. I didn't want to move the component docs at all (or others directly bound to some elements). Helped me a few times already :)


> Questions
>     * Some files will better be renamed, but this would break links in existing issues / discussions / branches (e.g. master).
>       Should the old files persist and only link to the new ones, or is this acceptable?

What would be your prefered way with the general docs? Delete the files or keep it and redirect?

**Comment by AlvinSchiller** [comment]
To merge the changes in the wiki repo:

a. Simple commandline:
- clone the original wiki from: https://github.com/MiczFlor/RPi-Jukebox-RFID.wiki.git
- pull changes from my wiki repo directly (fast forward possible): `git pull https://github.com/AlvinSchiller/RPi-Jukebox-RFID.wiki.git master`

b. To Merge with a prefered tools (like VS Code, ...):
- clone the original wiki from: https://github.com/MiczFlor/RPi-Jukebox-RFID.wiki.git
- add my wiki repo as a new remote 'AlvinSchiller': `git remote add AlvinSchiller https://github.com/AlvinSchiller/RPi-Jukebox-RFID.wiki.git`
- `git fetch --all`
- use the tool to pull / merge / rebase the changes from my wiki repo

**Comment by AlvinSchiller** [comment]
@s-martin @pabera
I saw that the gitter links are not valid anymore (404).
As gitter seems to be transformed to matrix should the linkes be deleted? Or create a matrix channel alternatively?

**Comment by pabera** [comment]
> As gitter seems to be transformed to matrix should the links be deleted? Or create a matrix channel alternatively?

Sounds like a good idea. We already have a Matrix Channel

* https://matrix.to/#/#phoniebox_smalltalk:matrix.org

**Comment by AlvinSchiller** [comment]
Ok, I looked a little further and apperantly the gitter room is still available at https://matrix.to/#/#phoniebox_community:gitter.im

So the URL should probably just be updated.

**Comment by pabera** [comment]
Should this be merged at some point?

**Comment by AlvinSchiller** [comment]
My wiki repo has been rebased on the latest changes.

**Comment by AlvinSchiller** [comment]
Raspberry Pi OS Bookworm was released a few days ago, which brings buster in oldoldstable state and also updates the imager software, so new flashes will most likely use bullseye (as the last issues/questions also show).

As there seem to be no bigger issues with bullseye, I would update the docs again to strip out Debian version names as much as possible, and would replace the bullseye warning on the installation page, with a warning that bookworm is currently not supported (https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2084).

Any concerns about breaking links with renaming wiki headers or the like?

**Comment by AlvinSchiller** [comment]
Also are there any know issues with 64bit in 2.x?
This is currently stated as unsupported in the docs but a lot users seem to use it.

**Comment by s-martin** [comment]
I think it’s ok to update the names and the links.

**Review by pabera — APPROVED** [review]

**Comment by pabera** [comment]
> I think it’s ok to update the names and the links.
> 
> I remember some issues reported, which were supposedly caused by 64bit, but right now I’m not sure, if 64 bit is really unsupported. @pabera were the 64 bit issues regarding future3?

It's not super supported at the moment. At the other side, I have not really tested it either. with 32bit, we are safe for now.

https://github.com/pabera/RPi-Jukebox-RFID/commit/99a5536db35692c84a487c74416f79af2f07fdf2

**Comment by s-martin** [comment]
I think we could merge this, after the conflicts have been solved.

**Comment by AlvinSchiller** [comment]
@s-martin I rebased the wiki repo with the latest changes as well. Should i push it now or are you on it?

**Comment by s-martin** [comment]
Please push it

**Comment by AlvinSchiller** [comment]
> Please push it

I dont have the needed right to push to the wiki :(

**Comment by s-martin** [comment]
I assume you mean this way https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages#adding-or-editing-wiki-pages-locally to push your changes?

I’ll look into it and then I will do it tonight or @MiczFlor grants you the rights and you can do it yourself - whatever happens first :)

N.B. I was today years old, when I learned that the wiki is just another git repo ;)

**Comment by AlvinSchiller** [comment]
HowTo is also here ->
https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2008#issuecomment-1537624099 
;)

Just a note: due do some files containing invalid characters the checkout (and therefor also push) is currently not possible on Windows.

**Comment by s-martin** [comment]
ok, looks like i pushed the wiki successfully : )

**Comment by AlvinSchiller** [comment]
Yes, looks good :)

**Pull request merged**
