### PR TITLE
omit inapropriate version evdev==0.7.0

### PR DESCRIPTION
**Pull request by t0b3**
see https://pypi.org/project/evdev/

### CODE REVIEW

**Comment by MiczFlor** [comment]
Hi @t0b3 
are you sure that this is not needed anymore? Did you do a fresh install? Because I had dropped this approx six months ago and the later versions of `evdev` did not work for me. ... ?

**Comment by t0b3** [comment]
Hi @MiczFlor 
I did a fresh install with the `raspberrypi-kernel-headers` corresponding the the `raspberrypi-kernel` already delivered in raspbian. It works like a charm here.

**Comment by MiczFlor** [comment]
Hi @t0b3 
I will check it myself some time soon - and then commit your changes.
Need to do a lot of testing on the develop branch anyhow... :)

**Comment by s-martin** [comment]
Did anyone try this recently?

**Comment by MiczFlor** [comment]
This has been solved in the version 2.0

**Pull request closed without merging**
