### PR TITLE
MQTT configuration is now in a dict for easier management

### PR DESCRIPTION
**Pull request by andreasbrett**
Improved usability for configuring the MQTT component based on a comment in the blog post mentioned here https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/1353#discussioncomment-1505100. Settings are now in a dict that allows commenting out unused configuration parameters (like e.g. mqttCA, mqttCert, mqttKey).

Thanks @splitti for the blog post and the hint that this could be improved.

**Note:** this is branched off of the to-be-merged https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/1496. Hope both can be merged in the upcoming 2.4 release.

### CODE REVIEW

**Comment by pabera** [comment]
@andreasbrett Would you also develop the MQTT extension for [future3](https://github.com/MiczFlor/RPi-Jukebox-RFID#-version-3-is-coming-)? 🤓

**Comment by andreasbrett** [comment]
Yes, this is on my list. Will wait a moment until futur3 is a bit less alpha though. Shouldn't be too many modifications but I only want to do it once the code base is more stable.

**Comment by ChisSoc** [comment]
> Yes, this is on my list. Will wait a moment until futur3 is a bit less alpha though. Shouldn't be too many modifications but I only want to do it once the code base is more stable.

Great! In Future3 we already have a Publisher Concept for immediate status publishing. No polling involved. So, the only thing a MQTT must do is listen to the publisher and translate the publish messages into the MQTT format. Vice versa for commands from MQTT to RPC. So this is a fair change from the Version 2. Still, it will be relatively easy to integrate. The hard question will be whether to  support the "old" MQTT topic names or switch to the topic names of the new Publisher. Once you want to start, feel free to drop me a message in the chat. I could point you to a good starting point (if needed).

**Comment by MiczFlor** [comment]
Hi @andreasbrett 
there is one conflict in this pull request now:

~~~

                # publish event "card_swiped"
<<<<<<< patch-5
                client.publish(config.get("mqttBaseTopic") + "/event/card_swiped", payload=cardid)
=======
                client.publish(mqttBaseTopic + "/event/card_swiped", payload=cardid)
>>>>>>> develop
                print(" --> Publishing event card_swiped = " + cardid)
~~~

**Comment by andreasbrett** [comment]
> Hi @andreasbrett there is one conflict in this pull request now:
> 
> ```
> 
>                 # publish event "card_swiped"
> <<<<<<< patch-5
>                 client.publish(config.get("mqttBaseTopic") + "/event/card_swiped", payload=cardid)
> =======
>                 client.publish(mqttBaseTopic + "/event/card_swiped", payload=cardid)
> >>>>>>> develop
>                 print(" --> Publishing event card_swiped = " + cardid)
> ```

should be fine now

**Comment by MiczFlor** [comment]
Merging -- but I can't test it myself... :) sorry...

**Pull request merged**
