### PR TITLE
fix(install): add missing python package

### PR DESCRIPTION
**Pull request by petschni**
Should address one of the issues mentioned in the following tickets:

- https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/1618
- https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/1788

### CODE REVIEW

**Comment by s-martin** [comment]
Hi, thanks for the PR.

that’s a little strange, because `evdev` should be installed here:
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/5084ace1f1077f04d4fae4640545e7df9b97f9d7/scripts/installscripts/buster-install-default.sh#L849

of course your PR works, but why does the pip install not work? Did you see something during a failed installation in the install logs?

**Comment by s-martin** [comment]
Maybe there’s a problem with Bullseye:
https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/1653#issuecomment-985765521

seems to work with Buster though

**Comment by petschni** [comment]
> Maybe there’s a problem with Bullseye: [#1653 (comment)](https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/1653#issuecomment-985765521)
> 
> seems to work with Buster though

saw that comment but actually for me the problem occurred also with Buster. I can try to reproduce it and see if I see any error in the log.

**Comment by s-martin** [comment]
I assume that’s the underlying issue #1791

**Comment by s-martin** [comment]
@petschni can you check, if #1791 solves your issue?

**Review by s-martin — CHANGES_REQUESTED** [review]
I think while this fixes the issue, the underlying issue is #1791

**Comment by petschni** [comment]
> I think while this fixes the issue, the underlying issue is #1791

@s-martin #1792 actually fixes the problem. However the following error is still thrown - but does not seem to impact the feature:

```
#
# INSTALLATION FINISHED
#
#####################################################

If you are using an RFID reader, connect it to your RPi.
(In case your RFID reader required soldering, consult the manual.)
Have you connected your RFID reader? [Y/n] 
Please select the RFID reader you want to use
1) USB-Reader (e.g. Neuftech)
2) RC522
3) PN532
4) Manual configuration
5) Multiple RFID reader
#? 1
Choose the reader from list
0 HXGCoLtd Keyboard
Device Number: 0
Exception ignored in: <function BaseEventLoop.__del__ at 0x761e08a0>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/base_events.py", line 622, in __del__
    warnings.warn(f"unclosed event loop {self!r}", ResourceWarning,
  File "/usr/lib/python3.7/asyncio/base_events.py", line 390, in __repr__
    f'<{self.__class__.__name__} running={self.is_running()} '
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1794, in get_debug
    return self._debug
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'

DONE. Let the sounds begin.
````

**Pull request closed without merging**
