### PR TITLE
Fix Spotify authentication 

### LINKED ISSUE #2429: 🐛 | Spotify changed authentication - Can't play content: GStreamer error: Could not get/set settings from/on resource
### Version

2.7.0 - 550a2583 - master

### Branch

master

### OS

Raspbian GNU/Linux 11 (bullseye) - Lite 32Bit

### Pi model

3 B Rev 1.2

### Hardware

* Raspberry Pi 3B
* HifiBerry DAC+

### What happened?

Installing Phoniebox works fine. When the box boots up, I can hear the boot-sound from the speakers fine also.
But when I play Spotify content via the WebUI or Iris, nothing plays and the following is written to the mopidy log:

`ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not get/set settings from/on resource.

### Logs

     ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not get/set settings from/on resource.

### Configuration

# mpd.conf

```
music_directory		"/home/pi/RPi-Jukebox-RFID/shared/audiofolders"
playlist_directory		"/home/pi/RPi-Jukebox-RFID/playlists"
db_file			"/var/lib/mpd/tag_cache"
log_file			"syslog"
pid_file			"/run/mpd/pid"
state_file			"/var/lib/mpd/state"
sticker_file                   "/var/lib/mpd/sticker.sql"
user				"root"
bind_to_address		"localhost"
log_level			"default"
auto_update    "yes"
auto_update_depth "10"
input {
        plugin "curl"
}
input {
        enabled    "no"
        plugin     "qobuz"
}
input {
        enabled      "no"
        plugin       "tidal"
}
decoder {
        plugin                  "hybrid_dsd"
        enabled                 "no"
}
audio_output {
	type		"alsa"
	name		"My ALSA Device"
	mixer_control	"DSP Program"		# optional
}
volume_normalization		"yes"
filesystem_charset		"UTF-8"
```

# /etc/mopidy/mopidy.conf

```
[core]
cache_dir = /var/cache/mopidy
config_dir = /etc/mopidy
data_dir = /var/lib/mopidy
max_tracklist_length = 10000
restore_state = false

[logging]
verbosity = 0
format = %(levelname)-8s [%(threadName)s] %(name)s %(message)s
color = false
config_file =

[audio]
mixer = software
mixer_volume = 30
output = alsasink
buffer_time =

[proxy]
scheme =
hostname =
port =
username =
password =

[file]
enabled = true
media_dirs =
  $XDG_MUSIC_DIR|Music
  ~/|Home
excluded_file_extensions =
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .pdf
  .png
  .txt
  .zip
show_dotfiles = false
follow_symlinks = false
metadata_timeout = 1

[http]
enabled = true
hostname = 0.0.0.0
port = 6680
zeroconf = Mopidy HTTP server on $hostname
allowed_origins =
csrf_protection = true
default_app = mopidy

[m3u]
enabled = true
base_dir =
default_encoding = UTF-8
default_extension = .m3u
playlists_dir = /home/pi/RPi-Jukebox-RFID/playlists

[softwaremixer]
enabled = true

[stream]
enabled = true
protocols =
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist =
timeout = 5000

[iris]
enabled = true
country = DE
locale = de_DE
verify_certificates = true
snapcast_enabled = true
snapcast_host = localhost
snapcast_port = 1780
snapcast_ssl = false
snapcast_stream = Default
spotify_authorization_url = https://jamesbarnsley.co.nz/iris/auth_spotify.php
lastfm_authorization_url = https://jamesbarnsley.co.nz/iris/auth_lastfm.php
genius_authorization_url = https://jamesbarnsley.co.nz/iris/auth_genius.php
data_dir = $XDG_DATA_DIR/iris

[local]
enabled = true
max_search_results = 100
media_dir = /home/pi/RPi-Jukebox-RFID/shared/audiofolders
scan_timeout = 1000
scan_flush_threshold = 100
scan_follow_symlinks = false
included_file_extensions =
excluded_file_extensions =
  .conf
  .jpg
  .txt
  placeholder
directories =
  Albums                  local:directory?type=album
  Artists                 local:directory?type=artist
  Composers               local:directory?type=artist&role=composer
  Genres                  local:directory?type=genre
  Performers              local:directory?type=artist&role=performer
  Release Years           local:directory?type=date&format=%25Y
  Tracks                  local:directory?type=track
  Last Week's Updates     local:directory?max-age=604800
  Last Month's Updates    local:directory?max-age=2592000
timeout = 10
use_artist_sortname = false
album_art_files =
  *.jpg
  *.jpeg
  *.png

[mpd]
enabled = true
hostname = 0.0.0.0
port = 6600
password =
max_connections = 20
connection_timeout = 60
zeroconf = Mopidy MPD server on $hostname
command_blacklist =
  listall
  listallinfo
default_playlist_scheme = m3u

[spotify]
enabled = true
username = <REMOVED>
password = ********
client_id = c9c9350b-<REMOVED>
client_secret = ********
bitrate = 160
volume_normalization = true
timeout = 10
allow_cache = true
cache_size = 8192
allow_playlists = true
search_album_count = 20
search_artist_count = 10
search_track_count = 50
```

### More info

Running the following as `root` and `user` mopidy works fine:

    gst-launch-1.0 playbin uri=file:///usr/share/sounds/alsa/Front_Center.wav

### PR DESCRIPTION
**Pull request by s-martin**
This should fix #2429.

- [x] gst plug-in needs to be updated in install-jukebox.sh (gst-plugin-spotify_0.14.0.alpha.1-1_armhf.deb), see also https://github.com/mopidy/mopidy-spotify/discussions/405#discussioncomment-10881114

Everyone experiencing this issue is invited to test this fix.

### CODE REVIEW

**Comment by s-martin** [comment]
To be checked https://github.com/mopidy/mopidy-spotify/issues/394#issuecomment-2401706956

**Comment by boboschkah** [comment]
Can someone please tell me what i have to do … i dont see the solution here!

**Comment by The-Judge** [comment]
> Can someone please tell me what i have to do … i dont see the solution here!

Hey @boboschkah , please find the solution here: https://github.com/mopidy/mopidy-spotify/discussions/405

**Comment by s-martin** [comment]
I can't test it, but from my point of view this could be merged.

**Review by pabera — APPROVED** [review]

**Pull request merged**
