### PR TITLE
Allow spaces in folder names (web app)

### PR DESCRIPTION
**Pull request by mamhoff**
This allows playing folders with spaces in them.

### CODE REVIEW

**Comment by MiczFlor** [comment]
Hi @mamhoff 
Thanks for your input. A small change with big impact!
Have you tried if the folder names with whitespaces work when using RFID chips? Your changes only affect the web interface and I seem to remember that somebody reported whitespaces should be avoided. Haven't tested it myself yet.

**Comment by mamhoff** [comment]
Yep, it did not work with the RFID chips at first, hence the second commit. We've been running this code on our jukebox today, and it seems to work! :)

**Comment by MiczFlor** [comment]
nice work, thanks!

**Comment by MiczFlor** [comment]
@mamhoff two small changes that I committed in the latest release:

- there was a typo in your pull request. To find files, the parameters are `-type f` not `type -f`
- I added sorting to the line, unix otherwise doesn't return a sensible list

**Comment by mamhoff** [comment]
Thank you. :)

**Pull request merged**
