### PR TITLE
Include workarounds to install mopidy 2.3.1 instead of mopidy 3 into install scripts

### PR DESCRIPTION
**Pull request by patrickweigelt**
Install libspotify-dev, mopidy 2.3.1 and tornado 5.0 as suggested in https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/700#issuecomment-570956201 and in https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/688#issuecomment-571129900 without actually installing mopidy 3 in the first place. Works for me (after some problems with `wget`) and is a way to make IRIS work until a version campatible with mopidy 3 is released.

### CODE REVIEW

**Comment by patrickweigelt** [comment]
Sorry @MiczFlor, I didn't see that you had changed it to the develop branch and thought I hade made a mistake. Changed it back to develop again now. The reason why I wanted to include it into the master branch is that I thought it would be good to have a working python 2.7 mopidy 2.3 install script while the develop branch is going into the python 3 mopidy 3 direction. Maybe that was a naive idea.

**Comment by MiczFlor** [comment]
Hi @patrickweigelt 
thanks for your contribution. What I am planning to do: add a "one line installer" to the wiki that uses the "develop" branch script, meaning your changes. Then merge to master asap, but there are a few other things I need to review first.
Could you make a pull request that does not conflict with the develop version of the script? Currently I am getting: **This branch has conflicts that must be resolved**

**Comment by patrickweigelt** [comment]
Hi @MiczFlor, I did, but I can only test it tonight. I hope it is appreciated because it adds back in a couple of things from master that seem to have been removed in develop probably on purpose towards mopidy 3? I had made my changes based on the script in master. Compared to my earlier attempt I also moved the installation of libspotify-dev back outside the Spotify part because @FloMrFrei mentioned it would also be needed for the non-spotify version which I never tried.

**Comment by FloMrFrei** [comment]
Hi @patrickweigelt, I have no idea if the libspotify-dev is required for the non-spotify version (from the name it seems not ;-) ) but it had to be installed because the one-line-installer would otherwise fail in any case and stop before installing the required packages.

**Pull request merged**
