### PR TITLE
Use correct branch for install test - was missed in #937

### PR DESCRIPTION
**Pull request by s-martin**
See #937

### CODE REVIEW

**Comment by MiczFlor** [comment]
@s-martin the failed checks. At what point to we need to worry about them? :)

**Comment by s-martin** [comment]
Once we got them running at least once :)

I wanted the PR #937 to be merged, because some files needed to be available on develop.

The current error (also for the failing Python Action) is caused by #924. We should decide, if we go back to the pypi installation there.

#924 currently breaks all installations from develop on a fresh SD card, where RPI.GPIO is not yet installed.

**Comment by MiczFlor** [comment]
Do we need #924 in the basic installation or should we push this into the `components` folder?

**Comment by s-martin** [comment]
I think pi-rc522 was always there, so moving to components would be unexpected for some users.

But from our architecture perspective it would belong to components.

One possibility would be to make a yes/no dialog in the install script, if something other than USB reader shall be used.

I think we already had a discussion about that with @fredg02 somewhere.

**Comment by MiczFlor** [comment]
Hm... if we move it to components, because it makes sense, the major version jump would be the best moment, I think.
Hi @fredg02 , it seems (@s-martin thinks so) that you have the expertise to assist moving the `pi-rc522` component out of the main install and into the components directory.
We discussed - and I guess that's the way to go - to finish the installation with an extra script which might handle available displays, RFID readers, soundcards.
If we do this, and work on an external script, it would be good to make sure the automated and interactive install procedure both work!
What do you think?

**Comment by fredg02** [comment]
Sounds good.

**Pull request merged**
