### PR TITLE
Fix experimental reader to be compatible with stable reader

### PR DESCRIPTION
**Pull request by alex-voigt**
Fixes problems with the experimental reader for non usb readers as discussed in #275

Now you can simply copy the Reader.py.experimental over the Reader.py and everything should work.

I also changed the copy command in the wiki because it didn't make sense to copy the stable reader over the experimental one:
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/RFID-Reader-Special

### CODE REVIEW

**Comment by alex-voigt** [comment]
Doesn't work like expected yet.. please wait merging this

**Comment by alex-voigt** [comment]
I am no python guy but I want to build a phoniebox for my daugther. Now I am really struggling with that shitty language ;-) Maybe someone can enlighten me and explain what I am doing wrong.

Taking a look at `daemon_rfid_reader.py`:
`reader.readCard()` is running the read action multiple times in row for no obvious reason to me. The added helper method on the Reader should make stuff compatible between stable and experimental reader.
If I am using the suggested `reader.reader.readCard()` suggested by @varac in the issue linked above it scans the card once and it just works.

**Comment by alex-voigt** [comment]
I tested with RC522 and USB reader now and it works for me...

**Comment by MiczFlor** [comment]
Hi @alex-voigt 
I will merge this to the `develop` branch now. Good work. Can you check if this works for you?

**Comment by alex-voigt** [comment]
Damn it. I messed something up. The Reader.py is now broken because it doesn't has the get_device method. The fix is here: https://github.com/alex-voigt/RPi-Jukebox-RFID/commit/ffa22323a485fc32af40a1025ed7d43cec175c7f

But I think the way to go should be using the experimental reader as the new stable one to get rid of all the trouble.

**Comment by MiczFlor** [comment]
Hi @alex-voigt 
thanks for the quick response. And I agree: experimental will become stable. In the past, some quick merged with master created chaos. Especially with the reader recognition. Which is why the develop branch is for testing. And experimental is for testing „the experimental“ ideas. Eventually experimental will be develop. And develop will be master. 
Your bug catch is part if the process and proof that the careful steps are the best way. 
Thanks for your contribution!
All the best, micz 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
