### PR TITLE
fixed formatting warnings

### PR DESCRIPTION
**Pull request by s-martin**

### CODE REVIEW

**Comment by MiczFlor** [comment]
Hi @s-martin 
what are you trying to improve / fix here?

**Comment by s-martin** [comment]
Only formatting changes for code style consistency.
Doesn't fix any actual bug.

**Comment by MiczFlor** [comment]
Hi @s-martin can you fix the conflict and merge it yourself? (I think you have the rights to merge?)

**Comment by s-martin** [comment]
Yes, will do.

**Comment by MiczFlor** [comment]
@s-martin 
looks like the conflicts are resolved. Will you merge or should I?

**Comment by s-martin** [comment]
I just want to reset some commits first. Many are doubled, because I messed up a merge.

**Pull request merged**
