### PR TITLE
Variable next is internal python code

### PR DESCRIPTION
**Pull request by splitti**
So i switched generally to variables beginning with btn_.

### CODE REVIEW

**Comment by MiczFlor** [comment]
@splitti 
great idea. Do you have this running locally?

**Comment by splitti** [comment]
Jep, already in my OLED repository. I also send a Pull request.

**Comment by kabakakao** [comment]
It's already fixed in #387

**Comment by splitti** [comment]
Look here (Master):
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/fb3e3f63c54d17f92ad6510d2320ddba6f920c05/misc/sampleconfigs/gpio-buttons.py.sample#L70

This file will be copied by the Onelineinstaller.

**Pull request merged**
