### PR TITLE
docker: update jukebox/mpd base image to debian:bookworm

### PR DESCRIPTION
**Pull request by notapirate**
* update all debian-based images to "bookworm" release (Debian 12)
* netcat package was removed, replace by virtual package netcat-openbsd

### CODE REVIEW

**Comment by pabera** [comment]
Thanks for the PR. We gotta be careful with this update for the time being as we just learned that Bookworm and it's new kernel do create a lot of churn (https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/2295) for both versions, v2 and v3. Hence, I'd postpone this merge until we have clarity about the next steps.

**Comment by notapirate** [comment]
Okay, I'm just proposing it because the update solved problems I had with pyzmq/libzmq

**Comment by pabera** [comment]
> solved problems I had with pyzmq/libzmq

Which problems are you referring to?

**Comment by notapirate** [comment]
I analysed it further and created an issue: #2302

**Pull request closed without merging**
