### PR TITLE
fixing log path

### PR DESCRIPTION
**Pull request by s-martin**
See issue #941

### CODE REVIEW

**Comment by fredg02** [comment]
Thanks for fixing that issue!

**Comment by MiczFlor** [comment]
Hi @s-martin 
this is because of docker?

**Comment by s-martin** [comment]
> Hi @s-martin
> this is because of docker?

I don't think so. I haven't tested a installation on a regular SD card yet, but not cloning into an existing dir should be the same.

**Comment by fredg02** [comment]
> Hi @s-martin 
> this is because of docker? 

This is a generic issue with Git cloning.
A workaround is changing to the directory and cloning to the current dir with ".":
`cd RPi-Jukebox-RFID
git clone https://github.com/MiczFlor/RPi-Jukebox-RFID.git .`

**Comment by MiczFlor** [comment]
@fredg02 @s-martin 
The path to the log file I understand. But the folder would need to be created somewhere?

**Comment by s-martin** [comment]
I would create the install log dir directly in the home folder.

**Pull request merged**
