### PR TITLE
Feature "sync shared"

### PR DESCRIPTION
**Pull request by AlvinSchiller**
I added a component to sync the shared files (shortcut and audiofolders) from a remote server via a mounted share or ssh.
It allows to manage the shortcuts and audiofiles of one to many Phonieboxes in a central place (e.g. NAS, one main Phoniebox, ...) in the network, but keeps the possibility to play audio offline once the data where synced.

There is a "full-sync" command that can be bound to an CardId and an optional "sync-on-rfid-scan" feature which syncs only the files for a CardId on scan (shortcuts and and the corresponding audiofolder). The "sync-on-rfid-scan" feature can also be enabled/disabled with a command bound to an CardId.

See "components/synchronisation/sync-shared/README.md" for further details.

### CODE REVIEW

**Comment by s-martin** [comment]
Hi, thanks for improving Phoniebox 🙏 

We will review the PR :) and are probably happy to add this feature.

please be aware that we are intending to move to Phoniebox 3 (future3 branches), which is an all python implementation. So you might want to consider to implement the feature there. 
Details: https://rpi-jukebox-rfid.readthedocs.io/en/latest/

**Comment by AlvinSchiller** [comment]
Thank you too for this great project :)
I read about future 3 and wasn't quite sure about the lifetime of 2.x.
But as I have no experience in python I made a start here. But I will try and get into it and add it for future 3 aswell.

**Comment by s-martin** [comment]
To be honest there is no clear "schedule" when version 3 will be the new stable.

**Comment by s-martin** [comment]
@AlvinSchiller, can you have a look?
Merge of #1968 now conflicts with this PR.

**Comment by AlvinSchiller** [comment]
@s-martin Merged it

**Comment by s-martin** [comment]
Note: we need to update the wiki as well after merging this PR: https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Sychnronising-Phonieboxes-in-a-local-network

**Pull request merged**
