### PR TITLE
Added check for ip within togglewifi function

### LINKED ISSUE #919: 🐛 | RFID Card to "toggle wifi" doesn't work
## Bug
I assigned a card ID to toggle wifi, but I can only toggle once (e.g. switch it on, but not off again)

### What I did
I'm running on version 2.0 rc7 classic (installed via buster install script). I'm trying to add a card ID to toggle wifi.
I found the existing function "togglewifi" in scripts/playout_controls.sh. 
I added the following lines to scripts/rfid_trigger_play.sh:
`$TOGGLEWIFI)
$PATHDATA/playout_controls.sh -c=togglewifi
;;
`
And these lines to settings/rfid_trigger_play.conf
`TOGGLEWIFI="0002173904"`
Then I swiped card ID 0002173904

### What happened
- Wifi is off.
- I swipe the card.
- Wifi is turned on.
/var/log/messages shows:
`raspberrypi rfkill: unblock set for type wifi
raspberrypi kernel: [ 6944.925978] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
raspberrypi kernel: [ 6944.925999] brcmfmac: power management disabled
raspberrypi kernel: [ 6946.316686] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready`
- after waiting several minutes, I swipe the card again.
- Wifi is NOT turned off.
/var/log/messages shows:
`raspberrypi rfkill: unblock set for type wifi`

Debug log shows the following after both swipes:
`########### SCRIPT rfid_trigger_play.sh (2020-04-23.20:34:56) ##
Card ID '0002173904' was used
########### SCRIPT playout_controls.sh (2020-04-23.20:34:57) ##
VAR COMMAND: togglewifi
VAR VALUE: 
Attempting to play: /home/pi/RPi-Jukebox-RFID/shared/audiofolders/
Type of play $VALUE: 
Path not found /home/pi/RPi-Jukebox-RFID/shared/audiofolders/`

### I expected this to happen

First swipe to activate Wifi (if it is initially off), second swipe to deactivate Wifi

If I run the script from the CLI, everything works fine:
`RPi-Jukebox-RFID/scripts/playout_controls.sh -c=togglewifi
Wifi will now be deactivated`
For further testing, I assigned separate card IDs for ENABLEWIFI and DISABLEWIFI, they both work as expected.

### Further information that might help
First swipe to activate Wifi which works:

> Apr 23 21:10:46 raspberrypi daemon_rfid_reader.py[3637]: Wifi will now be activated

> Apr 23 21:10:46 raspberrypi rfkill: unblock set for type wifi
> Apr 23 21:10:46 raspberrypi kernel: [ 8521.006526] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
> Apr 23 21:10:46 raspberrypi kernel: [ 8521.006545] brcmfmac: power management disabled
> Apr 23 21:10:46 raspberrypi systemd[1]: Starting Load/Save RF Kill Switch Status...
> Apr 23 21:10:46 raspberrypi daemon_rfid_reader.py[3637]: /home/pi/RPi-Jukebox-RFID/scripts/rfid_trigger_play.sh: line 326: [: too many arguments
> Apr 23 21:10:46 raspberrypi systemd[1]: Started Load/Save RF Kill Switch Status.
> Apr 23 21:10:48 raspberrypi dhcpcd[15087]: wlan0: carrier acquired
> Apr 23 21:10:48 raspberrypi kernel: [ 8522.379770] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
> Apr 23 21:10:48 raspberrypi dhcpcd[15087]: wlan0: IAID eb:5d:79:c5
> Apr 23 21:10:48 raspberrypi dhcpcd[15087]: wlan0: adding address fe80::ea43:b43c:8b14:3d48
> Apr 23 21:10:48 raspberrypi avahi-daemon[367]: Joining mDNS multicast group on interface wlan0.IPv6 with address fe80::ea43:b43c:8b14:3d48.
> Apr 23 21:10:48 raspberrypi avahi-daemon[367]: New relevant interface wlan0.IPv6 for mDNS.
> Apr 23 21:10:48 raspberrypi avahi-daemon[367]: Registering new address record for fe80::ea43:b43c:8b14:3d48 on wlan0.*.
> Apr 23 21:10:48 raspberrypi dhcpcd[15087]: wlan0: probing address 192.168.13.17/24
> Apr 23 21:10:48 raspberrypi dhcpcd[15087]: wlan0: soliciting an IPv6 router
> Apr 23 21:10:51 raspberrypi systemd[1]: systemd-rfkill.service: Succeeded.
> Apr 23 21:10:52 raspberrypi dhcpcd[15087]: wlan0: using static address 192.168.13.17/24
> Apr 23 21:10:52 raspberrypi avahi-daemon[367]: Joining mDNS multicast group on interface wlan0.IPv4 with address 192.168.13.17.
> Apr 23 21:10:52 raspberrypi dhcpcd[15087]: wlan0: adding route to 192.168.13.0/24
> Apr 23 21:10:52 raspberrypi dhcpcd[15087]: wlan0: adding default route via 192.168.13.1
> Apr 23 21:10:52 raspberrypi avahi-daemon[367]: New relevant interface wlan0.IPv4 for mDNS.
> Apr 23 21:10:52 raspberrypi avahi-daemon[367]: Registering new address record for 192.168.13.17 on wlan0.IPv4.
> Apr 23 21:11:01 raspberrypi dhcpcd[15087]: wlan0: no IPv6 Routers available

Second swipe to deactivate Wifi, which fails:

> Apr 23 21:11:07 raspberrypi daemon_rfid_reader.py[3637]: Wifi will now be activated
> Apr 23 21:11:07 raspberrypi rfkill: unblock set for type wifi
> Apr 23 21:11:07 raspberrypi daemon_rfid_reader.py[3637]: /home/pi/RPi-Jukebox-RFID/scripts/rfid_trigger_play.sh: line 326: [: too many arguments

By the way, line 326 of rfid_trigger_play.sh looks like this:
`if [ ! -z "$FOLDER" -a ! -z ${FOLDER+x} -a -d "${AUDIOFOLDERSPATH}/${FOLDER}" ]; then`

### Base image and version

`2020-02-13-raspbian-buster-lite.img`

### Branch / Release

master

### Installscript

/master/scripts/installscripts/buster-install-default.sh

### RaspberryPi version

3B Rev 1.2

### RFID Reader

16c0:27db HXGCoLtd Keyboard

### Soundcard

onboard

### Other notable hardware
```
GPIO Buttons:
shut = Button(3, hold_time=2)
vol0 = Button(13,pull_up=True)
volU = Button(16,pull_up=True,hold_time=0.3,hold_repeat=True)
volD = Button(19,pull_up=True,hold_time=0.3,hold_repeat=True)
next = Button(26,pull_up=True)
prev = Button(20,pull_up=True)
halt = Button(21,pull_up=True)
#reco = Button(6, pull_up=True) # Choose GPIO to fit your hardware
#play = Button(12,pull_up=True) # Choose GPIO to fit your hardware

shut.when_held = def_shutdown
vol0.when_pressed = def_vol0
volU.when_pressed = def_volU
#When the Volume Up button was held for more than 0.3 seconds every 0.3 seconds he will call a ra$
volU.when_held = def_volU
volD.when_pressed = def_volD
#When the Volume Down button was held for more than 0.3 seconds every 0.3 seconds he will lower t$
volD.when_held = def_volD
next.when_pressed = def_next
prev.when_pressed = def_prev
halt.when_pressed = def_halt
#reco.when_pressed = def_recordstart
#reco.when_released = def_recordstop
#play.when_pressed = def_recordplaylatest
```

### PR DESCRIPTION
**Pull request by Groovylein**
As requested from @MiczFlor I tried to implement the check IP into togglewifi to fix #919 .

The problem here is, I cannot test this setup since I don't have a spare RFID reader.

### CODE REVIEW

**Comment by MiczFlor** [comment]
Hi @Groovylein 
Thanks for the script. One question. Before opening my phoniebox to add keyboard and monitor if and when wlan is down, I ran this script on my phoniebox and my Ubuntu. 
Looks like your line
~~~
if [ $WIFI_SOFTBLOCK_RESULT -ne 0 ] && [ $WIFI_IP_RESULT -eq 0 ]
~~~
needs to be
~~~
if [ $WIFI_SOFTBLOCK_RESULT -eq 0 ] && [ $WIFI_IP_RESULT -eq 0 ]
~~~
?

Here is the Ubuntu version (using sudo):
~~~
rfkill list wifi | grep -i "Soft blocked: no"
rfkill list wifi | grep -i "Soft blocked: no" > /dev/null 2>&1
WIFI_SOFTBLOCK_RESULT=$?
sudo wpa_cli -i wlp4s0 status | grep 'ip_address'
sudo wpa_cli -i wlp4s0 status | grep 'ip_address' > /dev/null 2>&1
WIFI_IP_RESULT=$?
echo "   WIFI_IP_RESULT='${WIFI_IP_RESULT}' WIFI_SOFTBLOCK_RESULT='${WIFI_SOFTBLOCK_RESULT}'" 
if [ $WIFI_SOFTBLOCK_RESULT -eq 0 ] && [ $WIFI_IP_RESULT -eq 0 ]
then
    if [ "${DEBUG_playout_controls_sh}" == "TRUE" ]; then echo "   Wifi will now be deactivated" >> ${PATHDATA}/../logs/debug.log; fi
    echo "Wifi will now be deactivated"
    sudo rfkill block wifi
else
    if [ "${DEBUG_playout_controls_sh}" == "TRUE" ]; then echo "   Wifi will now be activated" >> ${PATHDATA}/../logs/debug.log; fi
    echo "Wifi will now be activated"
    sudo rfkill unblock wifi
fi
~~~
With these results:
~~~
	Soft blocked: no
ip_address=192.168.178.77
   WIFI_IP_RESULT='0' WIFI_SOFTBLOCK_RESULT='0'
Wifi will now be deactivated
~~~
or
~~~
Failed to connect to non-global ctrl_ifname: wlp4s0  error: No such file or directory
Failed to connect to non-global ctrl_ifname: wlp4s0  error: No such file or directory
   WIFI_IP_RESULT='1' WIFI_SOFTBLOCK_RESULT='1'
Wifi will now be activated
~~~

**Comment by Groovylein** [comment]
Did I get you right that with the `-eq` condition it works as expected?

I only transferred the following line:
```
$(rfkill list wifi | grep -i "Soft blocked: no")  > 0
```
to 
```
[ $WIFI_SOFTBLOCK_RESULT -ne 0 ]
```

**Comment by MiczFlor** [comment]
It works as expected on my Ubuntu. Haven't tried the Pi :)

I haven't dealt with this before and will do some testing later - I guess I have to open my Phoniebox :)

My thoughts: the IP address could be static or dynamic. Not sure if that makes a difference regarding the line
~~~
sudo wpa_cli -i wlan0 status | grep 'ip_address' > /dev/null 2>&1
~~~
... this might return an IP address if a static IP is set?

Need to do some work now, I mean *actual* work :)

**Comment by MiczFlor** [comment]
Seems to work now with the above settings. Tried it and get the correct behaviour (can't reach box via wifi) and correct log info:
~~~
########### SCRIPT playout_controls.sh (2020-05-22.15:19:15) ##
VAR COMMAND: togglewifi
VAR VALUE: 
   togglewifi
   WIFI_IP_RESULT='0' WIFI_SOFTBLOCK_RESULT='0'
   Wifi will now be deactivated
########### SCRIPT playout_controls.sh (2020-05-22.15:19:33) ##
VAR COMMAND: togglewifi
VAR VALUE: 
   togglewifi
   WIFI_IP_RESULT='1' WIFI_SOFTBLOCK_RESULT='1'
   Wifi will now be activated
~~~

**Pull request merged**
