### PR TITLE
included venv activation for python scripts

### PR DESCRIPTION
**Pull request by AlvinSchiller**
New PR for the venv activation problem adressed in https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2144
This implements the ideas from https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2144#discussion_r1421836778

* have "proxy" shell scripts that handle the venv activation and setup the needed working dir, to be run from any relativ path.
* better accessability of the scripts for the user, e.g. group with alike scripts like `installation` or `tools`
* run_*.py scripts can't be moved right now, as the module imports are not accessable from sub dirs, so they have to stay in the root folder. This could be a future addition (possible solution https://stackoverflow.com/a/50194143)

### CODE REVIEW

**Comment by s-martin** [comment]
Would it be a problem, if a user manually activates a venv and then runs a sh script, which also activates the venv?

**Comment by AlvinSchiller** [comment]
> Would it be a problem, if a user manually activates a venv and then runs a sh script, which also activates the venv?

Nope, tested multiple activations and couldn't see a sideeffect. The installations process does the same with the RFID Reader setup script.

**Review by pabera — APPROVED** [review]
Looks good. In another iteration, a way to abstract the repetition of the individual bash files could be to build a single installer script with an argument.

```
$ run.sh rpc_tool
$ run.sh publicity_sniffer
$ run.sh register_rfid_reader
```

This could then prepare again for Whiptail 🙃

**Comment by AlvinSchiller** [comment]
> Looks good. In another iteration, a way to abstract the repetition of the individual bash files could be to build a single installer script with an argument.
> 
> ```
> $ run.sh rpc_tool
> $ run.sh publicity_sniffer
> $ run.sh register_rfid_reader
> ```
> 
> This could then prepare again for Whiptail 🙃

Thought about that too 😁👍

**Comment by AlvinSchiller** [comment]
I will run some final test over this, otherwise ready to merge.

**Comment by pabera** [comment]
> Edit: Do we then need the motd message at all (#2225)?

Not for the reason of informing about the `venv`, but I truly believe we should keep this! 🚀

```
##################################################
   ___  __ ______  _  __________ ____   __  _  _
  / _ \/ // / __ \/ |/ /  _/ __/(  _ \ /  \( \/ )
 / ___/ _  / /_/ /    // // _/   ) _ ((  O ))  (
/_/  /_//_/\____/_/|_/___/____/ (____/ \__/(_/\_)

            Welcome to your Phoniebox
##################################################
```

**Comment by AlvinSchiller** [comment]
👍 i will update the Message to only have the banner :)

**Comment by AlvinSchiller** [comment]
With [this](https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2211#issuecomment-1923241614) condition that updates are broken and a fresh installation is needed, should we add this already to v3.5.0?

**Comment by pabera** [comment]
> ... should we add this already to v3.5.0?

Aligned!

**Review by s-martin — APPROVED** [review]

**Comment by AlvinSchiller** [comment]
Last fix included. Good to go, if nothing left.

**Comment by pabera** [comment]
Merge it!

**Pull request merged**
