### PR TITLE
command line script for linking RFID cards to folders & fixing broken links 

### PR DESCRIPTION
**Pull request by mtill**
organizeFiles: I added a small script for conveniently organizing audio folders, linking them to RFID cards, finding audio folders that are currently not bound to any RFID card, and fixing broken links.
I wrote this script as a replacement for the phoniebox-web-ui, since I'm running out of memory when using the web-ui on a raspberry pi zero. Using this small script significantly reduces resource usage on the system, so that works pretty well in my case.
Hope this might help someone.

### CODE REVIEW

**Comment by MiczFlor** [comment]
Hi @mtill 
looks great. Could you write a little "how to use" here as a comment? I am unsure if it makes sense to move these scripts to a subfolder in `scripts`. The folder is getting very cluttered :) @s-martin what do you think how to (a) locate this additional helper and (b) how to document it (wiki? docs folder?)

**Comment by mtill** [comment]
> Hi @mtill
> looks great. Could you write a little "how to use" here as a comment? I am unsure if it makes sense to move these scripts to a subfolder in `scripts`. The folder is getting very cluttered :) @s-martin what do you think how to (a) locate this additional helper and (b) how to document it (wiki? docs folder?)

hi, i added some remarks/documentation in the code/just invoke the script and pass "--help" as an argument

**Comment by s-martin** [comment]
I think `scripts` shouldn’t be used for additional tools as it contains the core.

Also `misc` would probably get cluttered.

maybe we need an additional tools directory?

**Comment by MiczFlor** [comment]
@s-martin 
or we move them into:
https://github.com/MiczFlor/RPi-Jukebox-RFID/tree/develop/scripts/helperscripts
?

**Comment by s-martin** [comment]
Yeah, that looks like a good place.

**Pull request merged**
