### PR TITLE
Replace Spotify oembed API request (outdated) by Mopidy API calls

### PR DESCRIPTION
**Pull request by danielhammer**
The previously integrated spotify oembed API is not supporting requests
for playlists anymore (currently tracks only). This led to empty playlist titles
and no covers. This code uses the already running Mopidy HTTP JSON-RPC API 
for getting title and covers thus not requiring any additional authentication
while still profiting of full Spotify API used by Mopidy.

### CODE REVIEW

**Comment by s-martin** [comment]
Thanks for fixing this. 

Minor improvement suggestion: create most parts of the curl command at one place, so this doesn't need to be done at multiple places.

**Comment by danielhammer** [comment]
> Thanks for fixing this.
> 
> Minor improvement suggestion: create most parts of the curl command at one place, so this doesn't need to be done at multiple places.

Thanks for the feedback @s-martin . You are absolutely right - lazy me! ;-)
Improved that by adding a function for API requests in Pull Request #953

**Comment by MiczFlor** [comment]
@danielhammer can this pull request be closed, because it's all now in #953?

**Comment by danielhammer** [comment]
updated version in #953 .
So I close this pull request.

**Pull request closed without merging**
