### PR TITLE
Bugfix #674 cant move / edit mp3

### PR DESCRIPTION
**Pull request by ctietze**

### CODE REVIEW

**Comment by MiczFlor** [comment]
Hi @ctietze 
do you have this running locally? I haven't tested it yet, won't have time until next week. But would like to know if this is the latest state of the art code from you?

**Comment by ctietze** [comment]
Hi @MiczFlor ,
yes I checked the issue #674 reported by @Reddi82 exists. I wrote two tests and tested it locally.
BR Clemens

**Comment by MiczFlor** [comment]
Hi @ctietze 
with "latest state of the art" I meant: your latest version as commits. Not the coding :) As you see, in Phoniebox, rule number one is: there are no rules :)

**Comment by ctietze** [comment]
:rofl: ok. Yes it was the last commit

**Pull request merged**
