### PR TITLE
(succeeded by #30 ) Added "resume playlist" functionality

### PR DESCRIPTION
**Pull request by Bockiii**
Major overhaul of the trigger file. Open for discussion :)

### CODE REVIEW

**Comment by princemaxwell** [comment]
Hey, great idea.
I tested it, but i had some issues.
One problem is, that some Files are having a ")" in it's filename and then the filename in *.track doesn't match, because "grep" is using ) as delimiter.
Can you fix this?

**Comment by Bockiii** [comment]
@princemaxwell Good catch, fixed that.

**Comment by MiczFlor** [comment]
@princemaxwell @Bockiii thanks guys. Lack of time requires me to delegate the authority for the decision to accept the pull requests to you :) the author and one peer reviewer. That should be good enough: can you both give me the thumbs up that this works?

One question regarding the new script: scripts/track_playstate.sh
https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/24/files

It states: "Do this every 5 seconds. Can be tuned but will lower accuracy"
Does this mean it needs to be set up with the cronjob? If so, can you add a paragraph here or as a pull request in the appropriate documentation file how to do this?

If it goes into the documentation, it should go into this chapter, I think?
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/docs/CONFIGURE.md#auto-start-the-jukebox

**Comment by Bockiii** [comment]
Hi @MiczFlor , thats okay for me.

It doesn't need to run in the cronjob as it's started by every card (and killed with every card). it's also only running during vlc is active (as to check if people kill vlc by web).

This is my first time using github so I will do this: open new  branch in my fork, commit all changes there and redo the PR as this one is kinda messy now. I will also add a note on how to use it in your documentation files (as a single trigger will restart last progress and double trigger will reset the playlist, that should be clarified).

**Comment by Bockiii** [comment]
I posted a new PR for the clean commit. I tested this with .txt files and it worked.

**Pull request closed without merging**
