### PR TITLE
Improve MPD logging configuration

### PR DESCRIPTION
**Pull request by s-martin**
Log mpd to syslog where everything else from Phoniebox is logged.
This reverts PR #989, which was just a first workaround.

Using syslog should be more sustainable. Log level is set to "default".

### CODE REVIEW

**Comment by s-martin** [comment]
I agree disabling logging or setting the log level is useful, if the Phoniebox shall run for a very long time.

**Comment by MiczFlor** [comment]
@s-martin can you have a look at the conflict? it seems trivial. Thanks

**Comment by s-martin** [comment]
Will do.

**Comment by s-martin** [comment]
@MiczFlor, conflicts are resolved now.

**Comment by s-martin** [comment]
@MiczFlor, if you don't have any comments we could merge it.

I think a general logging switch would be useful, but out of scope for this PR.

**Comment by s-martin** [comment]
Hey @MiczFlor, I think this PR would also fix #1055.

**Comment by MiczFlor** [comment]
Hi @s-martin thanks for the contribution. I will add this to develop now. It's been waiting for a long time. Like a good cheese :)

**Pull request merged**
