### PR TITLE
Fix spotify mopidy3 for buster

### PR DESCRIPTION
**Pull request by mikebarkmin**
# Changelog
- Use python3.7 as the default python
- Remove mopidy-iris (only temporarily until it supports python3. See for progress https://github.com/jaedb/Iris/issues/356)
- Remove custom mopidy-spotify
- Install mopidy-spotify, mopidy-mpd and mopidy-local from the mopidy repo

# Setup used for testing
- Raspbian Buster
- Neuftech USB Reader
- HifiBerry MiniAmp
- Play/Pause, Next, Prev, VolUp, VolDown GPIO Buttons

Maybe there are other setups which will break when using python3 as the default.

### CODE REVIEW

**Comment by JoeyRamone** [comment]
Would it make sense to use the workaround from #688 (plus pull request for it) instead and create a pull request if mopidy-iris is working with python3?

**Comment by MiczFlor** [comment]
Hi @mikebarkmin @JoeyRamone 
I would like to merge this with `develop` branch. Has anybody else tested it?
And @mikebarkmin you write "Maybe there are other setups which will break when using python3 as the default". Did it break anything?
Final question (because I do not use Spotify... possibly I need to bite the bullet and buy myself an account): without `mopidy-iris` is Spotify useable???

**Comment by domu83** [comment]
@Community: Anyone else here who wants to contribute for a year spotify prem account for @MiczFlor ? I think we face more and more issues and it would be really beneficial for all if @MiczFlor can debug with full access and I truley believe, that he should not pay on his own for our benefit!

I'm happy to throw a couple of € into the bucket

@MiczFlor... any idea on how to get you the money (e.g. paypal)?

**Comment by mikebarkmin** [comment]
@domu83 we could gift him Spotify Premium https://www.paypal.com/de/gifts/marken/spotify-digital. I am totally on-board in sponsoring a premium account for @MiczFlor.

**Comment by mikebarkmin** [comment]
@MiczFlor In my setup it did not break anything, but maybe you have written a script for phoniebox, which I am not using. I will check if all the phoniebox scripts will run under python3.

mopidy-iris is for finding out the unique spotify uri. This could also be done by using the desktop or web app of spotify.

**Comment by kingosticks** [comment]
Hi guys, forgive me as I am unfamiliar with this project but Mopidy-Spotify 4 is much improved (e.g. playlists now work again) and may provide what you need. If you can explain specifically when you want I can advise further.

**Comment by MiczFlor** [comment]
Hi @domu83 @mikebarkmin 
:) thanks for the supporting energy. Looks like a lot of work coming towards my inbox :) only kidding. I would be happy to indulge in spotify AND work on phoniebox more. At the same time: the local file situation is so much better for the eco footprint. Streaming is a climate killer... 
My current problem is time more than anything. I would not be able to start properly on diving in before March 2020.

**Comment by MiczFlor** [comment]
Hi @kingosticks 
insight would be good to have. And it looks like you have some experience.
The situation in short: Phoniebox (this repo) allows to link local mpd playlists to RFID chips, so they can be triggered by kids with not PC / keyboard interface. A web app is another way to trigger these files /playlists.
From the community, about a year ago, came the code base to link the Phoniebox to a spotify premium account and the RFID cards will then trigger the stream from the cloud rather than playling local files.
There is a little read for Spotify integration here: https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Spotify-FAQ
And somebody also provided a "howto" for the integration of Google Music:
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Enable-Google-Play-Music-GMusic
@domu83 @mikebarkmin : should we set up a thread here in the issue tracker to come up with a collective process and a pool of ideas?

**Comment by kingosticks** [comment]
I guess my question was really in the context of

> without mopidy-iris is Spotify useable

If I knew how you *used* Spotify and what Spotify features you need I could answer that.

**Comment by mikebarkmin** [comment]
mopdiy-iris allows to controll mopidy via a web interface. It supports local, spotify and other service. I guess the main use case is:

You want to link a rfid card with a spotify track. Therefore, you need to find out the spotify-uri. For example: spotify:track:2pnJ87yTVpkgtZh6Tq4vKh. With mopidy-iris you have a webinterface directly on the phoniebox to find the spotify-uri.

**Comment by kingosticks** [comment]
Thanks. So just a graphical interface for users to easily find the Spotify URI. Mopidy-Musicbox-Webclient displays URIs for tracks (but note that it doesn't currently display *playlist* URIs anywhere in the UI). I think Mopidy-Mobile also display them. So if you wanted to move to Mopidy 3, you could swap to using a different webclient, at until Iris becomes compatible.

Good luck with your project, please do ask at https://discourse.mopidy.com/ or https://mopidy.zulipchat.com/ if you have any problems with the upgrade (or anything else Mopidy related).

**Comment by ZyanKLee** [comment]
@MiczFlor @patrickweigelt  this PR has effectively been reverted by PR#720 was it intentional?

**Comment by patrickweigelt** [comment]
Half intentional I would say. I actually wanted to suggest to make some fixes on the master branch to make the old buster installer run with mopidy and IRIS again by installing mopidy 2.3.1-1 instead of 3 while on the develop branch everything could be prepared for mopidy 3. However, now that this is going on on the develop branch some steps to prepare for mopidy 3 have been undone I fear, as you noticed. I also commented on this below my pull requests because I didn't feel comfortable with it. Sorry if I caused confusion. Anyways, would it make sense to have two separate installer files on the develop branch: 1) for installing mopidy 2.3 and IRIS (the fixed old running version) which could after testing be pushed to the master branch and one for installing mopidy 3 and hopefully IRIS soon including the steps from this thread here?

**Comment by ZyanKLee** [comment]
> would it make sense to have two separate installer files on the develop branch

yeah - I think that would be the best choice. I'm thinking about some other options at the moment, but those will go into another issue.

**Pull request merged**
