### PR TITLE
Use functions, format if-conditions in install script

### PR DESCRIPTION
**Pull request by fredg02**
I have wrapped the different sections of the install script in functions and created a main function at the end. This makes it easier to test only a specific part/section of the install script, because big chunks can easily be commented out or in.

It looks like a lot of changes, but it's not. You can see that when using a diff program that is able to ignore white space changes. :)

### CODE REVIEW

**Comment by MiczFlor** [comment]
Hi @fredg02 
I like the idea very much. My first question, of course: did you test your work on a clean buster SD card? And: does it work?
(if you say yes, I will give it a try this weekend...)

**Comment by s-martin** [comment]
@fredg02, I like it very much, too! 

As @MiczFlor said, test on a fresh SD card is highly appreciated. For intermediate testing you could try the Docker images located in `./ci`, but hardware specific stuff can‘t really be tested with the images. @ZyanKLee could probably help with the images, if necessary.

I wanted to add a check in line 185, if the current installation has still the same commit hash as the repo, the user can decide, if a fresh installation is needed anyway. But I lack the appropriate bash skills, so if you want to take care of that, just go ahead.... :)

**Comment by fredg02** [comment]
> did you test your work on a clean buster SD card? And: does it work?
Yes, I've tested it with a clean buster SD card and it works AFAICT. As mentioned, if you ignore the white space changes, you can tell that this change does not change the "logic".

**Comment by fredg02** [comment]
> As @MiczFlor said, test on a fresh SD card is highly appreciated. For intermediate testing you could try the Docker images located in `./ci`, but hardware specific stuff can‘t really be tested with the images. @ZyanKLee could probably help with the images, if necessary.

Yes, testing with a fresh SD card does not scale. Will look into docker/emulator solutions.

> I wanted to add a check in line 185, if the current installation has still the same commit hash as the repo, the user can decide, if a fresh installation is needed anyway. But I lack the appropriate bash skills, so if you want to take care of that, just go ahead.... :)

Good idea. Since I have a couple of PRs in the queue that build on top of the current one, I'd like to push this back a little bit.

**Comment by MiczFlor** [comment]
I am merging this now to `develop`. It does need testing, which I will try in a few minutes, because @s-martin had some additions which I manually resolved. Sorry, if I broke anything :)

**Pull request merged**
