### PR TITLE
Dutch language file (first attempt)

### PR DESCRIPTION
**Pull request by iroQuai**
I guess 98% is translated correctly. Probably will edit some little things later on when using this some more...  Fine for everyday use!

### CODE REVIEW

**Comment by MiczFlor** [comment]
Hi @iroQuai 
there was a conflict with the UK language file. I fixed this locally and added your Dutch version. Thanks for the contribution!
It's currently only in the develop branch - I have to find the time to merge all the recent changes to master after thorough testing. Here is your work:
https://github.com/MiczFlor/RPi-Jukebox-RFID/tree/develop/htdocs/lang

**Comment by iroQuai** [comment]
I'm sorry, but this new file doesn't work at all for me.... It messes up the web app completely: changing the language file to nl-NL makes the whole web app blank. only way to change this back is to login via ssh and edit the Lang file to en-EN.

**Comment by MiczFlor** [comment]
Hi @iroQuai 
you are right, there was a typo in the file. Please try this one:
https://raw.githubusercontent.com/MiczFlor/RPi-Jukebox-RFID/develop/htdocs/lang/lang-nl-NL.php
and tell me if it works for you.
All the best, micz

**Comment by iroQuai** [comment]
it works! thanks for the fix :)

**Pull request closed without merging**
