### PR TITLE
Fix for #1133 (Update i2c_lcd.py to fix track number)

### PR DESCRIPTION
**Pull request by Conendrum**
see #1133

### CODE REVIEW

**Review by s-martin — APPROVED** [review]

**Comment by s-martin** [comment]
@SimonChelkowski, @davidfri could you take a look? Thanks

**Comment by davidfri** [comment]
Hi Conendrum!
I was able to reproduce the bug. Your solution tries to solve the problem afterwards, but the real problem is that we used the wrong variable. That's exactly what you've already noticed. We need to use the STATUS, not the CURRENT_SONG_INFOS. I would suggest the following:
I would change the line:
`                                track_number = current_song_infos['track']                                #
`
to
`                                track_number = str(int(status['song'])+1)                               #
`
So we continue to use the logic from mdc.
Here is the code part where i would change:
```
                else:
                        ########## GET MORE SONG-INFOS ####################################################
                        # This section reads in certain album informations                                #
                        #                                                                                 #
                        ## read in track number                                                           #
                        try:                                                                              #
                                track_number = str(int(status['song'])+1)                               #
                        except KeyError:                                                                  #
                                track_number = "1"             
```
Can your test this change on your system?
David

**Comment by Conendrum** [comment]
Hi @davidfri,

Thanks for the review! 

When trying to fix this bug, i indeed had a look at the "status" dictionary to see whether one of its keys was corresponding to the "track counter", but i had missed the "song" one. 
I tested your proposal and it's indeed working. As you said, it's a better approach as we keep using the mdc logic (and also less changes in the code!). I committed the change to reflect your proposal.
My approach was very likely already defined in the MDPClient library ;-)

Thanks and cheers

**Review by s-martin — APPROVED** [review]

**Comment by s-martin** [comment]
@davidfri, @Conendrum, so this works now? Then I would merge this PR.

**Comment by MiczFlor** [comment]
Hi @Conendrum @davidfri 
great work, thanks for the contribution!!!

**Pull request merged**
