### PR TITLE
hotfix: installer shall use master

### PR DESCRIPTION
**Pull request by s-martin**
With this fix, flake8 checks also work and should catch more issues (e.g. f-strings not in Python3.5 on stretch)

### CODE REVIEW

**Comment by MiczFlor** [comment]
@s-martin this is for master? not develop?

**Comment by s-martin** [comment]
Yes, it's in the python-phoniebox code, which isn't used right now anyway. But the missing `self` blocks flake from finding more issues, e.g. code not working with Python 3.5 on stretch.

**Comment by s-martin** [comment]
Hey @MiczFlor, I found an issue why the installers don't work anymore.

When the default branch in Github was set to `develop` this meant also that the installer scripts would use `develop`.

I just fixed this, this should be merged soon, because issues like #747 or #761 are probably affected by this.

This is just a hotfix, we need to find a suitable solution also for develop branch later.

**Comment by s-martin** [comment]
At least for one user it was confirmed in https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/747#issuecomment-581031783 that it works again.

**Comment by Thr33LittleBirds** [comment]
Hat funktioniert. Ich danke Euch

**Comment by s-martin** [comment]
I think @ZyanKLee already fixed this in develop.

**Pull request merged**
