### PR TITLE
fix: fixed all complaints of shellcheck

### PR DESCRIPTION
**Pull request by ZyanKLee**
I ran shellcheck and fixed all of the complaints it had about this 
script. Though at the moment I do not have a RPi to test the script is 
working correctly after my changes (I don't doubt it does run fine, but 
better be safe than sorry).

Example for shellcheck:

    docker run --rm -ti -v $PWD:/code -w /code pipelinecomponents/shellcheck:latest \
        shellcheck -x scripts/installscripts/buster-install-default.sh

### CODE REVIEW

**Comment by MiczFlor** [comment]
Hi @ZyanKLee 
I also need a Pi to test it. I wouldn't want to commit it to develop without testing. Did you get the time to test it?

**Comment by ZyanKLee** [comment]
not yet. hopefully the weekend will bring some spare time to do so.

**Comment by MiczFlor** [comment]
If so, there is a little conflict in there. Possibly you can make an updated pull request

**Comment by ZyanKLee** [comment]
as soon as #731 is working for me, I will test the script (in fact this is the ultimate test for #731, too)

**Comment by ZyanKLee** [comment]
aside from the to-be-expected errors from systemd (which is not yet working properly in the docker container) this script runs fine.

**Pull request merged**
