### PR TITLE
activation of shutdown button class in gpio_control

### LINKED ISSUE #1136: 🐛 | Shutdown via gpio_control executes immediately
## Bug

When pressing the shutdown button, the script for shutdown executes immediately.

### What I did

I installed the raspberry pi with above mentioned buster image and ran the installer script. I configures the gpio_settings.ini and changed the buttons to the classic layout. Every button works as expected but not the shutdown-button.

### What happened

Phoniebox shuts down immediately.

### I expected this to happen

I wanted to press the button at least 4 seconds before the shutdown begins. The LED should blink a few times (as in previous versions of Phoniebox).

### Further information that might help

This is, what I configured in the gpio_settings.ini. I am using open push buttons.

```
[Shutdown]
enabled: True
Type:  Button
Pin: 3
pull_up: True
hold_time: 4
functionCall: functionCallShutdown
```

### Base image and version

Raspbian GNU/Linux 10 (buster)

### Branch / Release

develop
up to date with 'origin/develop'.

### Installscript

scripts/installscripts/buster-install-default.sh

### RaspberryPi version

Raspberry Pi 3 Model B Rev 1.2

### RFID Reader

16c0:27db HXGCoLtd Keyboard

### Soundcard

1130:1620 Tenx Technology, Inc.

### Other notable hardware

GPIO Control Settings:
```[Shutdown]
enabled: True
Type:  Button
Pin: 3
pull_up: True
hold_time: 4
functionCall: functionCallShutdown
```

### PR DESCRIPTION
**Pull request by s-martin**
Fixes #1136

### CODE REVIEW

**Comment by veloxidSchweiz** [comment]
I have not really tested it. Only some tests with the pytest environment...

**Comment by s-martin** [comment]
@riekelcke, could you check, if these changes work for you?

**Comment by RiekeIcke** [comment]
Okay, I will try it in the next days.

**Comment by RiekeIcke** [comment]
So, I just implemented the changes and now the scripts runs after waiting for the time I configured. WoopWoop! :) Thanks!

But unfortunately the LED does not blink as in previous older versions. I am not sure, if it my fault, as I copied the changed lines manually into the files. I am a GitHub newbie... Is it possible to use a git command to copy the e.g. here 5 changed files and update them in the system? I would try it once more in the case that I can replace by this only the 5 changed files to get sure, that it was no manual fault.

**Comment by s-martin** [comment]
You could download all files here https://github.com/veloxidSchweiz/RPi-Jukebox-RFID/archive/feature/ShutdownButton.zip and then you need to take the 5 changed files and copy them to your Phoniebox

**Comment by RiekeIcke** [comment]
I need to set up a new test set and will come back, when I finished testing.

**Comment by s-martin** [comment]
@MiczFlor, I suggest to merge this PR to develop, so people can test it more easily.

**Comment by Toqqi** [comment]
I just implemented the file changes in my setup and this works fine!
Before that, I also had the issue of immediate shutdown after button press.
Now, I set a 5 seconds hold and it executes as expected.
Thank you!

**Pull request merged**
