### PR TITLE
Fix empty spotify cover and album title

### LINKED ISSUE #799: 🐛 | Spotify Name from Playlist not showing in Home View
### What I did

Linked a Card to a Spotify Playlist over website (iris)

### What happened

Linking is successfull but Name is not shown in the Home view

I've made a Screenshot from this. The Top Spotify List is marked with the yellow box from me. The second spotify is without that mark.
image

### I expected this to happen

Name shown in Home View

### Base image and version

2020-02-05-raspbian-buster-lite

### Branch / Release

 `master`

### Installscript

 `scripts/installscripts/buster-install-default.sh`

### RaspberryPi version

4b

### RFID Reader

Neuftech

### Soundcard

Hifiberry MiniAMP

### PR DESCRIPTION
**Pull request by lovethisshit**
* this modifies the requests for cover and album title to spotify by adding an empty header/context
* Fixes #799

### CODE REVIEW

**Comment by Hamsert** [comment]
I did these changes to the corresponding file on my Phoniebox, but it seems like it didn't fix the problems.

**Comment by s-martin** [comment]
I assume you did restart the webserver or reboot the Pi?

@lovethisshit can you help?

**Comment by Hamsert** [comment]
Yes I restarted the Pi after making the changes.

**Comment by lovethisshit** [comment]
Not sure, which version are you using?
I tried the solution mentioned here: https://stackoverflow.com/a/43750037 but it did work already without setting an explicit user agent. Maybe there is a system setting overriding this or saving the user agent?

**Comment by Hamsert** [comment]
> Edit: I forgot to mention, obviously you should delete all title.txt and cover.jpg files, because the code won't run if already present (or test it with a completely new folder)

This was the problem. After deleting the two files in my testfolder and rebooting the image and the title got loaded from spotify.

**Comment by Hamsert** [comment]
One more thing: if I remember correctly it also used to show the cover of tracks I directly started from iris. Right now it just shows the last image of things I played earlier when I start something from iris. I probably have to delete another file as well, but which?
Thanks!

**Comment by lovethisshit** [comment]
I think this is unrelated to this pull request, as the code i changed only writes the cover and title files. I might have time to look into this this week.

**Comment by Hamsert** [comment]
Alright, thanks!

**Pull request merged**
