### PR TITLE
Adapt pbc.c to current json rpc spec

### PR DESCRIPTION
**Pull request by sklemer1**
Just added 'package' to rpc json and provided a cli option for it.

### CODE REVIEW

**Comment by s-martin** [comment]
Could we merge this?

**Comment by pabera** [comment]
There is no harm with this implementation if I analyse this correctly. But the JSON RPC spec does NOT have a `package` pattern, as far as I can see that.

* https://www.jsonrpc.org/specification

@sklemer1 Maybe you can help us understand where this is coming from?

**Comment by s-martin** [comment]
@pabera 
I get this error:
```
pi@phoniebox:~/RPi-Jukebox-RFID/src/cli_client $ ./pbc -o "{ "jsonrpc": "2.0", "method": "host.shutdown" }"
Received {"error": {"code": -1, "message": "Missing mandatory parameter 'package'."}, "id": 123} (87 Bytes)
```

so it seems package is necessary, although I didn't find it in the spec

**Comment by sklemer1** [comment]
It is some time since I addes this -- the reason was that the JSON from Phonie-Box used these 'package' attributes where as the cli client did not. I haven't looked into the specification -- I saw the need as ist was used in the real world implementation :).

**Comment by s-martin** [comment]
Thanks for clarification.

**Pull request merged**
