### PR TITLE
Integrate scripts to install RC522 and PN532 reader

### PR DESCRIPTION
**Pull request by s-martin**
This should make the installation more easy and avoid confusion, e.g. #1001 

I tested installation on a docker image (which worked fine), but not with real reader hardware, because I don't have any reader available.

### CODE REVIEW

**Comment by MiczFlor** [comment]
Hi @s-martin I need to try this, too. But don't have the time for that right now.
Have you done a fresh install with this version on a Pi, not just docker?

**Comment by s-martin** [comment]
I didn't test it on a fresh install, because I need another SD card for fresh installs first.

**Comment by veloxidSchweiz** [comment]
I tested it today with a fresh installation on raspbian lite using an rc522 spi device
seems to work fine

**Comment by veloxidSchweiz** [comment]
@s-martin : Maybe it makes sense that one the Reader.py file is not actually copied, but instead only a symlink is used ( to the corresponding Reader.py{.original,.experimental,.kkdaemonRFIDreader})
and add the link to github, but do not track changes in that file

**Comment by s-martin** [comment]
@veloxidSchweiz: I think that's a good idea. Right now I can't test this, but I would help with a PR.

**Comment by MiczFlor** [comment]
@veloxidSchweiz @s-martin 
hm, let's discuss this a little. I prefer to copy the files, because that way, tinkering with the code does not hurt the git repo. And if something good comes from it, it can still be committed via the original file.
What's the advantage of the symlink?

**Comment by veloxidSchweiz** [comment]
I don't know what you mean 'tinkering will not hurt',
The reader.py is part of the repo, therefore it will affect the repo...
I would actually prefer to get only a single Reader.py the way with multiple files feels really strange to me. 
I have the impression that by using a symlink updates of the repo could be easier performed without harming the installation...

**Comment by s-martin** [comment]
My thoughts:

Symlinks:
+ The "correct", elegant Linux way
+ Easier version control
- Difficult to understand for inexperienced users

Copying files:
+ Easy for inexperienced users
- Could clutter local git workspace

In general one single Reader.py file, which handles all the cases would improve maintainability or some kind of plugin/interface system (see #792) would be the best way.

Symlinks and copying could be both avoided, if we aim for something "bigger", however that would require some effort and testing capabilities.

**Pull request merged**
