### PR TITLE
Update buster-install-default.sh

### PR DESCRIPTION
**Pull request by DonPavlov**
use $SUDO_USER because the raspberry pi imager tool creates different usernames now

### CODE REVIEW

**Comment by AlvinSchiller** [comment]
Hey, this is a great addition and this would address some open issues (like https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/1785).

But the change is sadly not sufficient, as throughout many files the user "pi" is hardcoded (like in Home_Dir Paths, chown commands and service definitions). These would need to be changed aswell to make all part of phoniebox work with a different user.

**Comment by AlvinSchiller** [comment]
Comments to the change:
- the changes should be made to the develop branch as this has the latest changes and merges will be made for a future release.
- the "$SUDO_USER" Variable is only set if the installation is actually called with "sudo ...", otherwise it is empty. So this should be adressed with $USER as fallback ("${SUDO_USER:-$USER}") or the command "logname" could be used.
- the changes to "sudo sed -i "s%/home/pi%${HOME_DIR}%g" ... " are not correct, as this replaces already all "/home/pi" occurences in these file with the current ${HOME_DIR}.

**Review by s-martin — CHANGES_REQUESTED** [review]
Please base the PR on `develop` branch.
Could you also consider the comments by @AlvinSchiller?

**Comment by DonPavlov** [comment]
will reopen pull new pull request with desired changes applied to develop

**Comment by DonPavlov** [comment]
Ok I took a closer look at everything. I am not sure we can that easily replace the user pi with something else. 
It just doesn't work. For e.g. All the .service files need adjustments.
The python scripts need to be reworked so they can accept different usernames. And use the relative home directory.
Too many things to fix at once.

**Comment by pabera** [comment]
It's not worth it for 2.x, I think!

**Comment by s-martin** [comment]
> It's not worth it for 2.x, I think!

I agree

**Pull request closed without merging**
