### PR TITLE
Enhance docker buster image

### PR DESCRIPTION
**Pull request by Groovylein**
while installing RPi-Jukebox-RFID in docker I get a lot of
`debconf: falling back to frontend: Readline`
Messages.

Found a fix and implemented it:
https://github.com/phusion/baseimage-docker/issues/58#issuecomment-47995343

Linked issue: #715

### CODE REVIEW

**Comment by Groovylein** [comment]
Not sure if it is necessary for stretch. I will test and update it accordingly

**Comment by ZyanKLee** [comment]
ah ... too late.

it would be better to set
```
DEBIAN_FRONTEND=noninteractive
```
right in the RUN section you need it. That way you can still use the interactive frontend when you are manually testing with the dockerimage

**Comment by s-martin** [comment]
Just make a new PR 😉

**Comment by ZyanKLee** [comment]
yeah, as soon as I got my hands on a running computer and the time to patch this up.
but if you beat me to it, I won't complain.

**Pull request merged**
